version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.8-management
    ports:
      - 5672:5672  # порт для доступа к RabbitMQ
      - 15672:15672  # порт для доступа к RabbitMQ Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq  # сохранение данных RabbitMQ
    environment:
      - RABBITMQ_DEFAULT_USER=admin  # имя пользователя для RabbitMQ
      - RABBITMQ_DEFAULT_PASS=admin123  # пароль для RabbitMQ
volumes:
  rabbitmq_data: